services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
      target: build
    command: npm run dev
    ports:
      - '3030:3000/tcp'
      - '9229:9229/tcp'
    volumes:
      - .:/opt:delegated
    environment:
      - MONGO_URI
      - SERVER_NAME=vACDM local dev server
      - PUBLIC_URL=http://localhost:3030
      - PORT=3000
      - VATSIM_AUTH_URL=https://auth-dev.vatsim.net
      - CLIENT_ID=652
      - CLIENT_SECRET=CcjuDBhLylxN60WXYYyurhd9wKBXfW5jD4n36fXk
      - ALLOW_SIM=true
      - ALLOW_OBS_MASTER=true
      - LOG_LEVEL_CONSOLE=debug
      - LOG_LEVEL_FILE=none
      - ECFMP_PLUGIN_URL=https://flow-dev.ecfmp.net/api/v1/plugin
      - FRONTEND_PROXY=http://frontend:5173/
      - ADMIN_CIDS=10000010,10000004
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
      args:
        - NODE_ENV=development
    command: npm run spa-dev
    volumes:
      - .:/opt:delegated
      - node_modules:/opt/node_modules:delegated
  nats:
    image: bitnami/nats:latest
    command: -config /etc/nats-server.conf
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - ./assets/nats-server.conf:/etc/nats-server.conf:ro
volumes:
  node_modules:
