services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
      target: build
    command: npm run dev
    ports:
      - '3030:3000/tcp'
      - '9229:9229/tcp'
    volumes:
      - .:/opt:delegated
    environment:
      - MONGO_URI
      - SERVER_NAME=vACDM local dev server
      - PUBLIC_URL=http://localhost:3030
      - PORT=3000
      - VATSIM_AUTH_URL=https://auth-dev.vatsim.net
      - CLIENT_ID=652
      - CLIENT_SECRET=CcjuDBhLylxN60WXYYyurhd9wKBXfW5jD4n36fXk
      - ALLOW_SIM=true
      - ALLOW_OBS_MASTER=true
      - LOG_LEVEL_CONSOLE=debug
      - LOG_LEVEL_FILE=none
      - FRONTEND_PROXY=http://frontend:5173/
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: npm run spa-dev
    volumes:
      - .:/app:delegated
