http_port: 8222

authorization {
    users [
        {
            user: "server"
            permissions {
                subscribe: ">"
                publish: ">"
            }
        }, {
            user: "client"
            permissions {
                subscribe: "vacdm.>"
                publish: "vacdm-client.>"
            }
        }
    ]
}

no_auth_user: "server"

websocket {
    port: 6222
    no_tls: true

    no_auth_user: "client"
}